name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      prerelease:
        description: 'Set TRUE for pre-release'
        required: false
        default: 'FALSE'

jobs:

  release:
    name: Publish a new release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Generate changelog from latest release
        id: changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.event.inputs.version }}"
          release_name: "Versione ${{ github.event.inputs.version }}"
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease == 'TRUE' }}

      - name: Archive release code
        run: |
          docker run --name "gs_release" ghcr.io/trinko/giuaschool:latest tests/docker/release.sh
          docker cp gs_release:/var/www/giuaschool/giuaschool-release.zip giuaschool-release-latest.zip

      - name: Publish latest release code
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: giuaschool-release-latest.zip
          asset_name: giuaschool-release-latest.zip
          tag: "v${{ github.event.inputs.version }}"

      - name: Add version tag to documentation
        run: |
          mkdir docs
          echo "tag: ${{ github.event.inputs.version }}" > docs/version.yml

      - name: Add version tag to documentation
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'docs/version.yml'
          destination_repo: 'trinko/giuaschool-docs'
          destination_branch: 'master'
          destination_folder: '_data'
          user_name: ${{ github.actor }}
          user_email: '${{ github.actor }}@users.noreply.github.com'
          commit_message: 'Add version tag to documentation'

      - name: Generate changelog pages
        run: |
          rm -f docs/*.yml
          #####----- latest release page
          echo "---" > docs/latest-release.md
          echo "layout: default" >> docs/latest-release.md
          echo "title: Ultima versione" >> docs/latest-release.md
          echo "nav_order: 10" >> docs/latest-release.md
          echo "---" >> docs/latest-release.md
          echo "" >> docs/latest-release.md
          echo "# Ultima versione"  >> docs/latest-release.md
          echo "{: .text-center .fw-400 .pb-5}" >> docs/latest-release.md
          echo "" >> docs/latest-release.md
          echo "Versione: {{ site.data.version.tag }}" >> docs/latest-release.md
          echo "" >> docs/latest-release.md
          echo "Data e ora di rilascio: `TZ='Europe/Rome' date +'%d/%m/%Y %H:%M'`" >> docs/latest-release.md
          echo "" >> docs/latest-release.md
          echo "Lista delle modifiche incluse nella nuova versione:"  >> docs/latest-release.md
          echo "" >> docs/latest-release.md
          echo "${{ steps.changelog.outputs.changelog }}"  >> docs/latest-release.md
          #####----- latest build page
          echo "---" > docs/latest-build.md
          echo "layout: default" >> docs/latest-build.md
          echo "title: 'Ultimo aggiornamento'" >> docs/latest-build.md
          echo "nav_order: 11" >> docs/latest-build.md
          echo "---" >> docs/latest-build.md
          echo "" >> docs/latest-build.md
          echo "# Ultimo aggiornamento"  >> docs/latest-build.md
          echo "{: .text-center .fw-400 .pb-5}" >> docs/latest-build.md
          echo "" >> docs/latest-build.md
          echo "Nessuna modifica dal rilascio dell'ultima versione" >> docs/latest-build.md

      - name: Add changelog pages to documentation
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'docs/.'
          destination_repo: 'trinko/giuaschool-docs'
          destination_branch: 'master'
          user_name: ${{ github.actor }}
          user_email: '${{ github.actor }}@users.noreply.github.com'
          commit_message: 'Add changelog pages to documentation'
